
CREATE TABLE topicos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(200) NOT NULL UNIQUE,
    mensaje VARCHAR(650) NOT NULL UNIQUE,
    fecha_creacion DATETIME NOT NULL,
    status VARCHAR(50) NOT NULL,
	autor_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(autor_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY(curso_id) REFERENCES cursos(id) ON DELETE CASCADE
)ENGINE=InnoDB;
